version: '3.8'

services:
  consumer:
    image: consumer:latest
    container_name: consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: test
  # TODO: Spark for batch processing

  # TODO: FastAPI server

volumes:
  minio_data:
    driver: local
  postgres_data: