version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9090:9090"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    # volumes:
    #   - ./data/minio:/data
    command: server --console-address ":9090" /data

  # TODO: Kafka

  # TODO: Spark for batch processing

  # TODO: Flask as API server

volumes:
  minio_data: