services:
  consumer:
    image: consumer:latest
    container_name: consumer
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: test
    depends_on:
      kafka:
        condition: service_healthy

  producer:
    image: producer:latest
    container_name: producer
    depends_on:
      - consumer
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: test
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  # TODO: Spark for batch processing

  # TODO: FastAPI server