services:
  consumer:
    image: consumer:latest
    container_name: consumer
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: streaming
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      kafka:
        condition: service_healthy

  producer:
    image: producer:latest
    container_name: producer
    depends_on:
      - consumer
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: streaming
    ports:
      - "8001:8000"

  backend:
    image: backend:latest
    container_name: backend
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"

  frontend:
    image: frontend:latest
    container_name: frontend
    ports:
      - "3000:80"

  spark-master:
    image: spark-server:latest
    container_name: spark-master
    environment:
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_UI_PORT=8080
      - SPARK_RPC_AUTHENTICATION_ENABLED=false
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    ports:
      - "8089:8080" # Spark UI
      - "7077:7077" # Spark Master port
    volumes:
      - spark-data:/opt/bitnami/spark
      - ./spark-server:/scripts
      - ./data:/data

  spark-worker:
    image: spark-server:latest
    container_name: spark-worker
    environment:
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
    depends_on:
      - spark-master
    volumes:
      - spark-data:/opt/bitnami/spark
      - ./spark-server:/scripts
      - ./data:/data

  spark-submit:
    image: spark-server:latest
    container_name: spark-submit
    depends_on:
      spark-master:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - JAVA_HOME=/opt/bitnami/java
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_LOCAL_DIRS=/tmp/spark-temp
      - MINIO_ADDRESS=minio
      - MINIO_PORT=9000
      - MINIO_USER=miniouser
      - MINIO_PASSWORD=miniopassword
      - POSTGRES_ADDRESS=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC_BATCH=batch_processing
      - KAFKA_TOPIC_STREAM=streaming
      - KAFKA_TOPIC_PREDICTION=predictions
    entrypoint: [
        "/bin/bash",
        "-c",
        "
        echo 'Submitting Streaming Job...';
        spark-submit --master spark://spark-master:7077 /scripts/streaming-data-handling.py # add & will run in background, for test, remove it.

        echo 'Waiting for 24 hours before batch processing...';
        # sleep 86400;

        echo 'Running Batch Processing...';
        # spark-submit --master spark://spark-master:7077 --jars /tmp/postgresql-*.jar /scripts/batch-processing.py;

        echo 'Running Model Training...';
        # spark-submit --master spark://spark-master:7077 --jars /tmp/postgresql-*.jar /scripts/model-training.py;
        ",
      ]
    volumes:
      - spark-data:/opt/bitnami/spark
      - ./spark-server:/scripts
      - ./data:/data

volumes:
  minio_data:
    driver: local
  postgres_data:
  spark-data:
